### ISSUE TITLE
ibmcloud plugin install kubernetes-service DOES NOT WORK

### ISSUE THREAD

**Issue by lapolonio** [ibm-cloud-docs/containers-cli-plugin#49]
`ibmcloud plugin install kubernetes-service`

running on mac OSX Catalina

> Looking up 'kubernetes-service' from repository 'IBM Cloud'...
> Plug-in 'container-service/kubernetes-service 1.0.82' found in repository 'IBM Cloud'
> Attempting to download the binary file...
>  6.81 MiB / 21.71 MiB [=========================>------------------------------------------------------]  31.38% 1m26s
> FAILED
> Unable to download the plug-in binary from the URL https://plugins.cloud.ibm.com/downloads/bluemix-plugins/container-service/1.0.82/container-service-darwin-amd64-1.0.82.
> Error: read tcp 10.0.0.235:49488->170.225.15.112:443: read: connection reset by peer
> Try again later.

**Comment by artberger** [comment]
@lapolonio sorry to see that you were experiencing connection issues.

You might try the `update` command if you already have the plug-in, `ibmcloud plugin update kubernetes-service`

I think that this issue is from the `ibmcloud` CLI, not the `ks` plug-in, so you could also try posting in their repo: https://github.com/ibm-cloud-docs/cli/issues/new

I see that there were internally some connection issues yesterday, so if you try this again, do you receive the same error? It might just have been temporary.

**Comment by lapolonio** [comment]
Thanks
